### ISSUE TITLE
エラー発生

### ISSUE THREAD

**Issue by tamaitomoaki** [abeyuya/actions-mention-to-slack#143]
普段から、こちらのactionにお世話になっております。

問題なく使用できていたのですが、エラーが発生し、動かなくなってしまったようです。

ご確認いただけますでしょうか？

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/19403777/137277644-4346db91-ce18-4921-9738-2fd8aa142243.png">

**Comment by abeyuya** [comment]
私のテスト環境でも再現しました
調査中なのですが、まだ原因わからない状態です

取り急ぎ v2.6 を指定してもらえれば動くことは確認できました

**Comment by abeyuya** [comment]
fix https://github.com/abeyuya/actions-mention-to-slack/pull/147
please use `v2` or `v2.8`
