### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by salmon-p** [abeyuya/actions-mention-to-slack#175]

**Comment by rohitjoshixyz** [comment]
I am getting the same issue

**Comment by rohitjoshixyz** [comment]
I resolved it by removing the `dist` folder from git ignore and pushing it to my forked repo

**Comment by abeyuya** [comment]
Yes, you need dist folder if you forked.
In this repository, `release` branch include dist folder and many users use it.
https://github.com/abeyuya/actions-mention-to-slack/tree/release/dist
