### ISSUE TITLE
What is needed to mention works on Slack?

### ISSUE THREAD

**Issue by lucianomlima** [abeyuya/actions-mention-to-slack#246]
Hi, I'm trying to setup slack mention action on github but I can't receive the messages in channel.
What my webhook need to do to action mention in a channel?
From the Workflow builder I can create a webhook workflow and choose the channel but I need to create a message text too and I don't know if I need to put a variable or not. Should I create an app intead?

Can you guide me ou show me an example?

**Comment by abeyuya** [comment]
@lucianomlima  Thank you for your interest in this library.

> Should be modified from <@ID> to <!subteam^ID> to work.

Thanks for the info, I will consider updating the README.

> It would also be great if it was possible to customize the message.

This is a very interesting feature. Specifically, do you want to customize the following message?

https://github.com/abeyuya/actions-mention-to-slack/blob/96335df1710737ca88287353e7435b9fd35a2955/src/main.ts#L76

https://github.com/abeyuya/actions-mention-to-slack/blob/96335df1710737ca88287353e7435b9fd35a2955/src/main.ts#L162

**Comment by lucianomlima** [comment]
I can open a pull request for the user group slack mention change.

Regarding the change in messages, what do you think of adding the messages in the action settings in the yml file?

**Comment by abeyuya** [comment]
@lucianomlima  Thank you!!
